# Sample configuration for emby_extractor

[paths]
# Update the paths below to match your environment.
download_root = "C:/Media/Download"
extracted_root = "C:/Media/Extracted"
finished_root = "C:/Media/Finished"

[options]
finished_retention_days = 14
enable_delete = false
demo_mode = false

[tools]
# Provide the path to 7-Zip (or compatible) for extracting RAR archives.
seven_zip = "C:/Program Files/7-Zip/7z.exe"